### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RahulPangambam** [liuch37/pan-tensorflow#1]
I am getting this error

Traceback (most recent call last):
  File "train.py", line 136, in <module>
    for iter, data in enumerate(train_dataloader):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 483, in __iter__
    for item in (self[i] for i in range(len(self))):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 483, in <genexpr>
    for item in (self[i] for i in range(len(self))):
  File "/content/drive/My Drive/pan-tensorflow/dataset/ctw1500.py", line 367, in __getitem__
    data = self.prepare_train_data_single(global_idx)
  File "/content/drive/My Drive/pan-tensorflow/dataset/ctw1500.py", line 252, in prepare_train_data_single
    bboxes, words = get_ann(img, gt_path)
  File "/content/drive/My Drive/pan-tensorflow/dataset/ctw1500.py", line 36, in get_ann
    with open(gt_path, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: './data/train_labels/0390.txt'

**Comment by liuch37** [comment]
Please make sure to download and put correct dataset (e.g. /CTW1500 in your case) in ./data. You can check how it is handled in ctw1500.py.

**Comment by RahulPangambam** [comment]
Thank you for your response. I did try as you said but I am still getting an error. This time it is 0517.txt. Below provided is the directory

/content/drive/My Drive/pan-tensorflow/data/CTW1500/train/train_labels
[13]
ls
0001.xml  0127.xml  0253.xml  0378.xml  0503.xml  0629.xml  0755.xml  0881.xml
0002.xml  0128.xml  0254.xml  0379.xml  0504.xml  0630.xml  0756.xml  0882.xml
0003.xml  0129.xml  0255.xml  0380.xml  0505.xml  0631.xml  0757.xml  0883.xml
0004.xml  0130.xml  0256.xml  0381.xml  0506.xml  0632.xml  0758.xml  0884.xml
0005.xml  0131.xml  0257.xml  0382.xml  0507.xml  0633.xml  0759.xml  0885.xml
0006.xml  0132.xml  0258.xml  0383.xml  0508.xml  0634.xml  0760.xml  0886.xml
0007.xml  0133.xml  0259.xml  0384.xml  0509.xml  0635.xml  0761.xml  0887.xml
0008.xml  0134.xml  0260.xml  0385.xml  0510.xml  0636.xml  0762.xml  0888.xml
0009.xml  0135.xml  0261.xml  0386.xml  0511.xml  0637.xml  0763.xml  0889.xml
0010.xml  0136.xml  0262.xml  0387.xml  0512.xml  0638.xml  0764.xml  0890.xml
0011.xml  0137.xml  0263.xml  0388.xml  0513.xml  0639.xml  0765.xml  0891.xml
0012.xml  0138.xml  0264.xml  0389.xml  0514.xml  0640.xml  0766.xml  0892.xml
0013.xml  0139.xml  0265.xml  0390.xml  0515.xml  0641.xml  0767.xml  0893.xml
0014.xml  0140.xml  0266.xml  0391.xml  0516.xml  0642.xml  0768.xml  0894.xml
0015.xml  0141.xml  0267.xml  0392.xml  0517.xml  0643.xml  0769.xml  0895.xml
0016.xml  0142.xml  0268.xml  0393.xml  0518.xml  0644.xml  0770.xml  0896.xml
0017.xml  0143.xml  0269.xml  0394.xml  0519.xml  0645.xml  0771.xml  0897.xml
0018.xml  0144.xml  0270.xml  0395.xml  0520.xml  0646.xml  0772.xml  0898.xml
0019.xml  0145.xml  0271.xml  0396.xml  0521.xml  0647.xml  0773.xml  0899.xml
0020.xml  0146.xml  0272.xml  0397.xml  0522.xml  0648.xml  0774.xml  0900.xml
0021.xml  0147.xml  0273.xml  0398.xml  0523.xml  0649.xml  0775.xml  0901.xml
0022.xml  0148.xml  0274.xml  0399.xml  0524.xml  0650.xml  0776.xml  0902.xml
0023.xml  0149.xml  0275.xml  0400.xml  0525.xml  0651.xml  0777.xml  0903.xml
0024.xml  0150.xml  0276.xml  0401.xml  0526.xml  0652.xml  0778.xml  0904.xml
0025.xml  0151.xml  0277.xml  0402.xml  0527.xml  0653.xml  0779.xml  0905.xml
0026.xml  0152.xml  0278.xml  0403.xml  0528.xml  0654.xml  0780.xml  0906.xml
0027.xml  0153.xml  0279.xml  0404.xml  0529.xml  0655.xml  0781.xml  0907.xml
0028.xml  0154.xml  0280.xml  0405.xml  0530.xml  0656.xml  0782.xml  0908.xml
0029.xml  0155.xml  0281.xml  0406.xml  0531.xml  0657.xml  0783.xml  0909.xml
0030.xml  0156.xml  0282.xml  0407.xml  0532.xml  0658.xml  0784.xml  0910.xml
0031.xml  0157.xml  0283.xml  0408.xml  0533.xml  0659.xml  0785.xml  0911.xml
0032.xml  0158.xml  0284.xml  0409.xml  0534.xml  0660.xml  0786.xml  0912.xml
0033.xml  0159.xml  0285.xml  0410.xml  0535.xml  0661.xml  0787.xml  0913.xml
0034.xml  0160.xml  0286.xml  0411.xml  0536.xml  0662.xml  0788.xml  0914.xml
0035.xml  0161.xml  0287.xml  0412.xml  0537.xml  0663.xml  0789.xml  0915.xml
0036.xml  0162.xml  0288.xml  0413.xml  0538.xml  0664.xml  0790.xml  0916.xml
0037.xml  0163.xml  0289.xml  0414.xml  0539.xml  0665.xml  0791.xml  0917.xml
0038.xml  0164.xml  0290.xml  0415.xml  0540.xml  0666.xml  0792.xml  0918.xml
0039.xml  0165.xml  0291.xml  0416.xml  0541.xml  0667.xml  0793.xml  0919.xml
0040.xml  0166.xml  0292.xml  0417.xml  0542.xml  0668.xml  0794.xml  0920.xml
0041.xml  0167.xml  0293.xml  0418.xml  0543.xml  0669.xml  0795.xml  0921.xml
0042.xml  0168.xml  0294.xml  0419.xml  0544.xml  0670.xml  0796.xml  0922.xml
0043.xml  0169.xml  0295.xml  0420.xml  0545.xml  0671.xml  0797.xml  0923.xml
0044.xml  0170.xml  0296.xml  0421.xml  0546.xml  0672.xml  0798.xml  0924.xml
0045.xml  0171.xml  0297.xml  0422.xml  0547.xml  0673.xml  0799.xml  0925.xml
0046.xml  0172.xml  0298.xml  0423.xml  0548.xml  0674.xml  0800.xml  0926.xml
0047.xml  0173.xml  0299.xml  0424.xml  0549.xml  0675.xml  0801.xml  0927.xml
0048.xml  0174.xml  0300.xml  0425.xml  0550.xml  0676.xml  0802.xml  0928.xml
0049.xml  0175.xml  0301.xml  0426.xml  0551.xml  0677.xml  0803.xml  0929.xml
0050.xml  0176.xml  0302.txt  0427.xml  0552.xml  0678.xml  0804.xml  0930.xml
0051.xml  0177.xml  0302.xml  0428.xml  0553.xml  0679.xml  0805.xml  0931.xml
0052.xml  0178.xml  0303.xml  0429.xml  0554.xml  0680.xml  0806.xml  0932.xml
0053.xml  0179.xml  0304.xml  0430.xml  0555.xml  0681.xml  0807.xml  0933.xml
0054.xml  0180.xml  0305.xml  0431.xml  0556.xml  0682.xml  0808.xml  0934.xml
0055.xml  0181.xml  0306.xml  0432.xml  0557.xml  0683.xml  0809.xml  0935.xml
0056.xml  0182.xml  0307.xml  0433.xml  0558.xml  0684.xml  0810.xml  0936.xml
0057.xml  0183.xml  0308.xml  0434.xml  0559.xml  0685.xml  0811.xml  0937.xml
0058.xml  0184.xml  0309.xml  0435.xml  0560.xml  0686.xml  0812.xml  0938.xml
0059.xml  0185.xml  0310.xml  0436.xml  0561.xml  0687.xml  0813.xml  0939.xml
0060.xml  0186.xml  0311.xml  0437.xml  0562.xml  0688.xml  0814.xml  0940.xml
0061.xml  0187.xml  0312.xml  0438.xml  0563.xml  0689.xml  0815.xml  0941.xml
0062.xml  0188.xml  0313.xml  0439.xml  0564.xml  0690.xml  0816.xml  0942.xml
0063.xml  0189.xml  0314.xml  0440.xml  0565.xml  0691.xml  0817.xml  0943.xml
0064.xml  0190.xml  0315.xml  0441.xml  0566.xml  0692.xml  0818.xml  0944.xml
0065.xml  0191.xml  0316.xml  0442.xml  0567.xml  0693.xml  0819.xml  0945.xml
0066.xml  0192.xml  0317.xml  0443.xml  0568.xml  0694.xml  0820.xml  0946.xml
0067.xml  0193.xml  0318.xml  0444.xml  0569.xml  0695.xml  0821.xml  0947.xml
0068.xml  0194.xml  0319.xml  0445.xml  0570.xml  0696.xml  0822.xml  0948.xml
0069.xml  0195.xml  0320.xml  0446.xml  0571.xml  0697.xml  0823.xml  0949.xml
0070.xml  0196.xml  0321.xml  0447.xml  0572.xml  0698.xml  0824.xml  0950.xml
0071.xml  0197.xml  0322.xml  0448.xml  0573.xml  0699.xml  0825.xml  0951.xml
0072.xml  0198.xml  0323.xml  0449.xml  0574.xml  0700.xml  0826.xml  0952.xml
0073.xml  0199.xml  0324.xml  0450.xml  0575.xml  0701.xml  0827.xml  0953.xml
0074.xml  0200.xml  0325.xml  0451.xml  0576.xml  0702.xml  0828.xml  0954.xml
0075.xml  0201.xml  0326.xml  0452.xml  0577.xml  0703.xml  0829.xml  0955.xml
0076.xml  0202.xml  0327.xml  0453.xml  0578.xml  0704.xml  0830.xml  0956.xml
0077.xml  0203.xml  0328.xml  0454.xml  0579.xml  0705.xml  0831.xml  0957.xml
0078.xml  0204.xml  0329.xml  0455.xml  0580.xml  0706.xml  0832.xml  0958.xml
0079.xml  0205.xml  0330.xml  0456.xml  0581.xml  0707.xml  0833.xml  0959.xml
0080.xml  0206.xml  0331.xml  0457.xml  0582.xml  0708.xml  0834.xml  0960.xml
0081.xml  0207.xml  0332.xml  0458.xml  0583.xml  0709.xml  0835.xml  0961.xml
0082.xml  0208.xml  0333.xml  0459.xml  0584.xml  0710.xml  0836.xml  0962.xml
0083.xml  0209.xml  0334.xml  0460.xml  0585.xml  0711.xml  0837.xml  0963.xml
0084.xml  0210.xml  0335.xml  0461.xml  0586.xml  0712.xml  0838.xml  0964.xml
0085.xml  0211.xml  0336.xml  0462.xml  0587.xml  0713.xml  0839.xml  0965.xml
0086.xml  0212.xml  0337.xml  0463.xml  0588.xml  0714.xml  0840.xml  0966.xml
0087.xml  0213.xml  0338.xml  0464.xml  0589.xml  0715.xml  0841.xml  0967.xml
0088.xml  0214.xml  0339.xml  0465.xml  0590.xml  0716.xml  0842.xml  0968.xml
0089.xml  0215.xml  0340.xml  0466.xml  0591.xml  0717.xml  0843.xml  0969.xml
0090.xml  0216.xml  0341.xml  0467.xml  0592.xml  0718.xml  0844.xml  0970.xml
0091.xml  0217.xml  0342.xml  0468.xml  0593.xml  0719.xml  0845.xml  0971.xml
0092.xml  0218.xml  0343.xml  0469.xml  0594.xml  0720.xml  0846.xml  0972.xml
0093.xml  0219.xml  0344.xml  0470.xml  0595.xml  0721.xml  0847.xml  0973.xml
0094.xml  0220.xml  0345.xml  0471.xml  0596.xml  0722.xml  0848.xml  0974.xml
0095.xml  0221.xml  0346.xml  0472.xml  0597.xml  0723.xml  0849.xml  0975.xml
0096.xml  0222.xml  0347.xml  0473.xml  0598.xml  0724.xml  0850.xml  0976.xml
0097.xml  0223.xml  0348.xml  0474.xml  0599.xml  0725.xml  0851.xml  0977.xml
0098.xml  0224.xml  0349.xml  0475.xml  0600.xml  0726.xml  0852.xml  0978.xml
0099.xml  0225.xml  0350.xml  0476.xml  0601.xml  0727.xml  0853.xml  0979.xml
0100.xml  0226.xml  0351.xml  0477.txt  0602.xml  0728.xml  0854.xml  0980.xml
0101.xml  0227.xml  0352.xml  0477.xml  0603.xml  0729.xml  0855.xml  0981.xml
0102.xml  0228.xml  0353.xml  0478.xml  0604.xml  0730.xml  0856.xml  0982.xml
0103.xml  0229.xml  0354.xml  0479.xml  0605.xml  0731.xml  0857.xml  0983.xml
0104.xml  0230.xml  0355.xml  0480.xml  0606.xml  0732.xml  0858.xml  0984.xml
0105.xml  0231.xml  0356.xml  0481.xml  0607.xml  0733.xml  0859.xml  0985.xml
0106.xml  0232.xml  0357.xml  0482.xml  0608.xml  0734.xml  0860.xml  0986.xml
0107.xml  0233.xml  0358.xml  0483.xml  0609.xml  0735.xml  0861.xml  0987.xml
0108.xml  0234.xml  0359.xml  0484.xml  0610.xml  0736.xml  0862.xml  0988.xml
0109.xml  0235.xml  0360.xml  0485.xml  0611.xml  0737.xml  0863.xml  0989.xml
0110.xml  0236.xml  0361.xml  0486.xml  0612.xml  0738.xml  0864.xml  0990.xml
0111.xml  0237.xml  0362.xml  0487.xml  0613.xml  0739.xml  0865.xml  0991.xml
0112.xml  0238.xml  0363.xml  0488.xml  0614.xml  0740.xml  0866.xml  0992.xml
0113.xml  0239.xml  0364.xml  0489.xml  0615.xml  0741.xml  0867.xml  0993.xml
0114.xml  0240.xml  0365.xml  0490.xml  0616.xml  0742.xml  0868.xml  0994.xml
0115.xml  0241.xml  0366.xml  0491.xml  0617.xml  0743.xml  0869.xml  0995.xml
0116.xml  0242.xml  0367.xml  0492.xml  0618.xml  0744.xml  0870.xml  0996.xml
0117.xml  0243.xml  0368.xml  0493.xml  0619.xml  0745.xml  0871.xml  0997.xml
0118.xml  0244.xml  0369.xml  0494.xml  0620.xml  0746.xml  0872.xml  0998.xml
0119.xml  0245.xml  0370.xml  0495.xml  0621.xml  0747.xml  0873.xml  0999.xml
0120.xml  0246.xml  0371.xml  0496.xml  0622.xml  0748.xml  0874.xml  1000.xml
0121.xml  0247.xml  0372.xml  0497.xml  0623.xml  0749.xml  0875.xml
0122.xml  0248.xml  0373.xml  0498.xml  0624.xml  0750.xml  0876.xml
0123.xml  0249.xml  0374.xml  0499.xml  0625.xml  0751.xml  0877.xml
0124.xml  0250.xml  0375.xml  0500.xml  0626.xml  0752.xml  0878.xml
0125.xml  0251.xml  0376.xml  0501.xml  0627.xml  0753.xml  0879.xml
0126.xml  0252.xml  0377.xml  0502.xml  0628.xml  0754.xml  0880.xml

Traceback (most recent call last):
  File "train.py", line 136, in <module>
    for iter, data in enumerate(train_dataloader):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 483, in __iter__
    for item in (self[i] for i in range(len(self))):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 483, in <genexpr>
    for item in (self[i] for i in range(len(self))):
  File "/content/drive/My Drive/pan-tensorflow/dataset/ctw1500.py", line 367, in __getitem__
    data = self.prepare_train_data_single(global_idx)
  File "/content/drive/My Drive/pan-tensorflow/dataset/ctw1500.py", line 252, in prepare_train_data_single
    bboxes, words = get_ann(img, gt_path)
  File "/content/drive/My Drive/pan-tensorflow/dataset/ctw1500.py", line 36, in get_ann
    with open(gt_path, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: './data/CTW1500/train/train_labels/0517.txt'

**Comment by liuch37** [comment]
Note that CTW1500 has two version of labeling - new one with .xml files and old one with .txt files. My code only supports the older version. You can either write your own dataloader to handle .xml files or look for old version dataset in their github.

**Comment by RahulPangambam** [comment]
can you please send the link for the older version dataset

**Comment by liuch37** [comment]
Check https://github.com/Yuliang-Liu/Curve-Text-Detector/blob/master/OLD_README.md and the link (https://1drv.ms/u/s!Aplwt7jiPGKilH4XzZPoKrO7Aulk) (OneDrive)

**Comment by RahulPangambam** [comment]
Thank you for your response. I am getting this error (I am doing my project in google colab)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[16,160,160,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:BiasAdd]

**Comment by RahulPangambam** [comment]
Thnak you very much for helping out
